# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-04-06 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pic',
            fields=[
                ('id', models.IntegerField(auto_created=True,  serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': '图片',
                'db_table': 'd_pic',
                'verbose_name': '图片',
            },
        ),
    ]
