# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-04-06 14:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_pic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pic',
        ),
    ]
